In [0]:
import numpy as np

In [0]:
a =np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [11]:
b=np.array([[1,2,3],[4,5,6]])
b
b.itemsize

8

In [6]:
a.dtype

dtype('int64')

In [16]:
c=np.array([1,2,3],dtype='int64')
c
c.dtype

dtype('int64')

In [17]:
c.itemsize

8

In [18]:
c.nbytes

24

In [19]:
c.ndim

1

In [0]:
##accesing te elements that in the array

In [28]:
b[0,2]

3

In [23]:
c[1]

2

In [0]:
d=np.array([[1,2,3,4,5,6,7,8,9,10],[2,3,4,5,6,7,8,9,10,11]])

In [41]:
d[:5,:5]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [44]:
d[0:5]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [46]:
mat=np.ones((4,4),dtype='int32')
mat

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [48]:
matzero=np.zeros((4,4))
matzero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
matfull=np.full((5,5),100)
matfull

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [53]:
newa=np.array([[[1,2,3]]])
print(newa)
newa.ndim

[[[1 2 3]]]


3

In [73]:
a=np.full((5,5),10)
a

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [66]:
a[0,:]=5
a

array([[ 5,  5,  5,  5,  5],
       [10, 10, 10, 10,  5],
       [10, 10, 10, 10,  5],
       [10, 10, 10, 10,  5],
       [10, 10, 10, 10,  5]])

In [67]:
a[:,4]=5
a

array([[ 5,  5,  5,  5,  5],
       [10, 10, 10, 10,  5],
       [10, 10, 10, 10,  5],
       [10, 10, 10, 10,  5],
       [10, 10, 10, 10,  5]])

In [0]:
b=np.full((2,2),5)

In [69]:
print(b)

[[5 5]
 [5 5]]


In [71]:
a=b
a

array([[5, 5],
       [5, 5]])

In [75]:
a[2:4,2:4]=b
a

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10,  5,  5, 10],
       [10, 10,  5,  5, 10],
       [10, 10, 10, 10, 10]])

In [76]:
print(b)

[[5 5]
 [5 5]]


In [80]:
b.reshape(1,4)

array([[5, 5, 5, 5]])

In [88]:
c=np.random.rand(4,2)
c

array([[0.83261664, 0.11942283],
       [0.50011452, 0.37504977],
       [0.94737117, 0.22516901],
       [0.08554718, 0.58922957]])

In [89]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [91]:
ar=np.array([[1,2,3]])
r1=np.repeat(ar,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [95]:
ar=np.array([[1,2,3]])
r1=np.repeat(ar,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [117]:
arr=np.full((5,5),1)
inar=np.full((3,3),0)
#inar
arr[1:4,1:4]=inar
arr[2,2]=9
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [132]:
a=np.array([1,2,3])

b=a.copy()
b
a*b
a**2


array([1, 2, 3])

In [128]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [129]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [130]:
np.matmul(a,b)

14

In [140]:
d=np.full((3,3),10)
#np.linalg.det(d)
d[0,1]=12
d[1,1]=9
d[1,2]=19
np.linalg.det(d)

180.0

In [143]:
np.max(d,axis=0)
#aix=0 is column 1 is row

array([10, 12, 19])

In [151]:
v1=np.array([1,2,43,67,5])
v2=np.array([2,3,100,42,5])
np.vstack([v1,v2])

array([[  1,   2,  43,  67,   5],
       [  2,   3, 100,  42,   5]])

In [152]:
pwd


'/content'

In [153]:
ls

sample_data/


In [156]:
filedata=np.genfromtxt('D:\data.txt',delimiter=',')

OSError: ignored